config/routes.rb
GroceApp::Application.routes.draw do
  root 'carts#index'

  resources :carts
end

app/models/cart.rb
class Cart < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	def index
		@carts = Cart.all
	end

	def show
		@cart = Cart.find(params[:id])
	end

	def new 
		@cart = Cart.new
	end

	def create
		@cart = Cart.create cart_params
		redirect_to cart_path(@cart)
	end

	def edit
		@cart = Cart.find(params[:id])
	end

	def update
		@cart = Cart.find(params[:id])
		@cart.update cart_params
		redirect_to cart_path(@cart)
	end

	def destroy
		Cart.find(params[:id]).destroy
		redirect_to root_path
	end

	private 
		def cart_params
			params.require(:cart).permit(:amount, :item, :description)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/edit.html.erb
<h1>Edit Your Food</h1>
<%= form_for @cart do |f| %>

	<%= label_tag(:amount, "Amount:") %>
	<%= f.number_field :amount %></br>

	<%= label_tag(:item, "Item:") %>
	<%= f.text_field :item %></br>

	<%= label_tag(:description, "Description:") %>
	<%= f.text_area :description %></br>

	<%= f.submit "Update" %>
<% end %>

app/views/carts/index.html.erb
<h1> Index Page! </h1>

<% @carts.each do |food| %>
	<li> 
		<%= link_to food.item, cart_path(food.id) %>
		<%= link_to "edit", edit_cart_path(food[:id]) %>
		<%= link_to "delete", food, method: :delete, data: { confirm: "You sure?" }%>
	</li>
<% end %>

<%= link_to "Add Item to Cart", new_cart_path %>

app/views/carts/new.html.erb
<h1>Add new food item</h1>
<%= form_for @cart do |f| %>
	<%= label_tag(:amount, "Amount:") %>
	<%= f.number_field :amount %></br>

	<%= label_tag(:item, "Item:") %>
	<%= f.text_field :item %></br>

	<%= label_tag(:description, "Description") %>
	<%= f.text_area :description %></br>
	
	<%= f.submit "Add" %>
<% end %>

app/views/carts/show.html.erb
<h1>What's in your Grocery Cart</h1>
<p>Amount: <%=@cart['amount'].to_s%></p>
<p>Item: <%= @cart['item']%></p>
<p>Description <%= @cart['description']%></p>

<%= link_to "Back to Grocery Cart",carts_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GroceApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>